# Numpy: Package of multidimantional array

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,4,5,6]
np.array(simple_list)

array([1, 2, 4, 5, 6])

In [3]:
arr=np.array(simple_list)

In [16]:
arr

array([1, 2, 4, 5, 6])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [18]:
np.zeros(5,str)

array(['', '', '', '', ''], dtype='<U1')

In [25]:
np.zeros(5,bool)

array([False, False, False, False, False])

In [20]:
np.ones(5,bool)

array([ True,  True,  True,  True,  True])

In [27]:
np.ones((2,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
np.zeros((2, 3),dtype=int,order='F')

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
np.arange(5,10) 

array([5, 6, 7, 8, 9])

In [44]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [50]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [62]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [53]:
np.random.rand(2,2)

array([[0.82574975, 0.04544754],
       [0.64246854, 0.25082695]])

In [54]:
ar=np.random.rand(2,2)
ar

array([[0.85011357, 0.00836532],
       [0.11691513, 0.89539047]])

In [58]:
np.random.randn(2,2)


array([[-0.11994171,  0.89087769],
       [-0.9184696 ,  0.67804191]])

In [60]:
np.random.randint(2,5)

4

In [61]:
np.random.randint(2,5,20)

array([4, 3, 4, 2, 3, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2, 4, 3, 3, 3, 2])

In [64]:
sample_array=np.arange(20)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
rand_num=np.random.randint(0,100,20)
rand_num

array([28, 24, 94, 56, 66, 68, 39, 57, 28, 28, 64, 38, 87, 50, 98, 44, 93,
       26, 30, 23])

In [71]:
rand_num.reshape(5,6)

ValueError: cannot reshape array of size 20 into shape (5,6)

In [70]:
rand_num.reshape(4,3)

ValueError: cannot reshape array of size 20 into shape (4,3)

In [72]:
rand_num.max()

98

In [73]:
rand_num.argmax()

14

In [75]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
a=np.random.rand(1,4)
a

array([[0.29500138, 0.73026375, 0.48385306, 0.84687708]])

In [97]:
a.T

array([[0.29500138],
       [0.73026375],
       [0.48385306],
       [0.84687708]])

In [98]:
sample_arr=np.arange(10,20)
sample_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [99]:
sample_arr[1]

11

In [101]:
sample_arr[2:8]

array([12, 13, 14, 15, 16, 17])

In [102]:
sample_arr[2:8]=100
sample_arr

array([ 10,  11, 100, 100, 100, 100, 100, 100,  18,  19])

In [103]:
sample_arr[2:8]=100,1,2,3,5,5
sample_arr

array([ 10,  11, 100,   1,   2,   3,   5,   5,  18,  19])

In [106]:
sample_arr[:]=10
sample_arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [108]:
sample_arr[2:4]=80

In [109]:
sample_arr

array([10, 10, 80, 80, 10, 10, 10, 10, 10, 10])

# Two dimentional array

In [110]:
matrx=np.array(([1,2,3],[4,5,6],[10,30,30]))

In [111]:
matrx

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 30, 30]])

In [113]:
matrx[0,0]

1

In [115]:
matrx[2,0]

10

In [116]:
matrx[2]

array([10, 30, 30])

In [120]:
matrx[:,(2,1)] # (2,1) means 2nd column and 1st column

array([[ 3,  2],
       [ 6,  5],
       [30, 30]])

In [126]:
matrx[2,:]

array([10, 30, 30])

In [127]:
matrx[2]

array([10, 30, 30])

# Selections Techniques

In [129]:
sample_array=np.arange(1,20)

In [130]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [131]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [134]:
np.exp(sample_array) 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [135]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [136]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [137]:
np.max(sample_array)

19

In [138]:
np.min(sample_array)

1

In [139]:
np.argmax(sample_array)

18

In [140]:
np.argmin(sample_array)

0

In [141]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [142]:
np.std(sample_array)

5.477225575051661

In [143]:
np.var(sample_array)

30.0

In [144]:
np.mean(sample_array)

10.0

In [146]:
array=np.random.randn(3,4)
array

array([[-1.21562713,  0.86425687, -0.38853702,  0.16428782],
       [ 0.75397299, -0.74992554, -3.04586091, -0.32152133],
       [ 0.28724885, -0.3167944 ,  0.09680142, -1.62761998]])

In [148]:
np.round(array,decimals=2) ###### rounding the decimals numbers

array([[-1.22,  0.86, -0.39,  0.16],
       [ 0.75, -0.75, -3.05, -0.32],
       [ 0.29, -0.32,  0.1 , -1.63]])

In [150]:
sports=np.array(["golf","criket","fball","criket"])
np.unique(sports)

array(['criket', 'fball', 'golf'], dtype='<U6')

In [152]:
sports=np.array([[1,2,2,2,2,3,4,5,6,7],[1,2,2,2,2,3,4,5,6,7]])
np.unique(sports)

array([1, 2, 3, 4, 5, 6, 7])